[tool.poetry]
name = "recipe-app-api"
version = "0.1.0"
description = ""
authors = ["yamil <yamil.muza@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
