name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # runner(OS) where the job will be running on.
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v1    # allows to use another pre-made action from the gitHub action repository
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # action provided by gitHub for free
        uses: actions/checkout@v4 # updated the action. If it doesn't work, return to v1
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test" # this command runs the wait_for_db command and the unit tests
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

